### ISSUE TITLE
[rework] Rework master ticket

### ISSUE THREAD

**Issue by aureq** [aureq/letslambda#40]
Tracking pending work
- [x] Simplify manual certificate issuance aureq/letslambda#36
- [x] Let's lambda fails and retry to issue certificates multiple times aureq/letslambda#38
- [x] SSH host declaration aureq/letslambda#37
- [x] Provide bundled PEM content into single file aureq/letslambda#41

* Let's Lambda renewal frequency
- [x] Allow more frequent invocation when adding new certs to YAML aureq/letslambda#35
- [x] Renewing certificate based on time window aureq/letslambda#39
- [x] Prevent generating new SSL certificate if the latest one is too recent aureq/letslambda#29
